---
# tasks file for nginx-settings

- name: Install epel-release
  yum: name=epel-release state=latest

- name: Create site folder
  file: path=/home/{{ domain_name }} state=directory

- name: Install Nginx
  yum: name=nginx state=latest

- name: Autostart webserver
  service: name=nginx state=started enabled=yes

- name: Generate HTTP nginx.conf
  template: src=nginx.j2 dest={{ nginx_config_remote }}/nginx.conf mode=0644
  notify: Reload nginx

- name: Generate virtual_host HTTP
  template: src=conf.d/host1.j2 dest={{ virtual_hosts_folder_remote }}/{{ domain_name }}.conf mode=0644
  notify: Reload nginx

- name: Generate title page
  template: src=index.j2 dest={{ site_folder_remote }}/{{ domain_name }}/index.html mode=0644

- name: Install certbot
  yum: name=certbot state=present

- name: Create LE folder
  file: path=/etc/letsencrypt state=directory

- name: Create letsencrypt certificate
  shell: certbot certonly -n --webroot -w /home/{{ domain_name }} -m {{ letsencrypt_email }} -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: Generate virtual_host HTTPS
  template: src=conf.d/host2.j2 dest={{ virtual_hosts_folder_remote }}/{{ domain_name }}.conf mode=0644
  notify: Reload nginx

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: certbot --renew certonly -n --webroot -w /home/{{ domain_name }} -m {{ letsencrypt_email }} -d {{ domain_name }} && service nginx reload

